# Generated by Django 6.0.4 on 2026-04-09 11:16

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_frontenduser_membership_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='质押方案名称', max_length=100, verbose_name='质押产品名称')),
                ('annual_rate', models.DecimalField(db_comment='质押产品的年化收益率，百分比', decimal_places=2, max_digits=5, verbose_name='年化收益率')),
                ('min_amount', models.DecimalField(db_comment='该产品允许的最低质押金额', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='最低质押金额')),
                ('max_amount', models.DecimalField(blank=True, db_comment='该产品允许的最高质押金额，可为空表示不限制', decimal_places=2, max_digits=20, null=True, verbose_name='最高质押金额')),
                ('duration_days', models.IntegerField(blank=True, db_comment='建议质押期限，留空表示不限期', null=True, verbose_name='质押期限(天)')),
                ('description', models.TextField(blank=True, db_comment='质押产品的补充说明', null=True, verbose_name='产品说明')),
                ('is_active', models.BooleanField(db_comment='是否在前台或后台可用', default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='质押产品创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '质押产品',
                'verbose_name_plural': '质押产品',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_comment='用户质押的余额金额', decimal_places=2, max_digits=20, verbose_name='质押金额')),
                ('annual_rate', models.DecimalField(db_comment='本次质押使用的年化收益率', decimal_places=2, max_digits=5, verbose_name='年化收益率')),
                ('start_at', models.DateTimeField(db_comment='质押启动时间', default=django.utils.timezone.now, verbose_name='开始时间')),
                ('last_settled_at', models.DateTimeField(blank=True, db_comment='最近一次质押收益结算时间', null=True, verbose_name='最后结算时间')),
                ('total_earned', models.DecimalField(db_comment='质押已结算的总收益', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='累计收益')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_comment='当前质押状态', default='active', max_length=20, verbose_name='质押状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='质押记录创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='质押记录更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_comment='发起质押的用户', on_delete=django.db.models.deletion.CASCADE, related_name='stakes', to='users.frontenduser', verbose_name='质押用户')),
                ('product', models.ForeignKey(db_comment='选择的质押产品', on_delete=django.db.models.deletion.PROTECT, related_name='stakes', to='staking.stakingproduct', verbose_name='质押产品')),
            ],
            options={
                'verbose_name': '质押记录',
                'verbose_name_plural': '质押记录',
                'ordering': ('-created_at',),
            },
        ),
    ]
