# Generated by Django 6.0.4 on 2026-04-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakingproduct',
            name='image',
            field=models.ImageField(blank=True, db_comment='质押产品的展示图片', null=True, upload_to='staking_products/', verbose_name='产品图片'),
        ),
    ]
