# Generated by Django 6.0.4 on 2026-04-09 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_comment='用户唯一手机号，用于登录', max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(db_comment='加密存储的登录密码', max_length=128, verbose_name='登录密码')),
                ('invite_code', models.CharField(db_comment='系统生成的唯一邀请码', max_length=10, unique=True, verbose_name='我的邀请码')),
                ('status', models.BooleanField(db_comment='True为正常, False为拉黑封禁', default=True, verbose_name='账号状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='用户注册的时间', verbose_name='注册时间')),
                ('referrer', models.ForeignKey(blank=True, db_comment='上级推荐人的ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.frontenduser', verbose_name='推荐人')),
            ],
            options={
                'verbose_name': '前台用户',
                'verbose_name_plural': '前台用户',
                'db_table': 'frontend_user',
            },
        ),
    ]
