# Generated by Django 6.0.4 on 2026-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='membership_level',
            field=models.IntegerField(db_comment='用户会员等级，1=普通会员，2=VIP，3=超级VIP等', default=1, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='pay_password',
            field=models.CharField(blank=True, db_comment='加密存储的支付密码，用于支付验证', max_length=128, null=True, verbose_name='支付密码'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='username',
            field=models.CharField(db_comment='用户昵称或显示名称', default='', max_length=50, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
