# Generated by Django 6.0.4 on 2026-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_frontenduser_membership_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_comment='Mini App / Telegram 登录时的 tg user id', null=True, unique=True, verbose_name='Telegram 用户 ID'),
        ),
        migrations.AddField(
            model_name='frontenduser',
            name='telegram_username',
            field=models.CharField(blank=True, db_comment='不含 @ 的 username，可能为空', max_length=64, null=True, verbose_name='Telegram 用户名'),
        ),
        migrations.AlterField(
            model_name='frontenduser',
            name='phone',
            field=models.CharField(blank=True, db_comment='可选；Telegram 登录用户可为空，手机号注册登录时必填', max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
    ]
