# Generated by Django 6.0.4 on 2026-04-24 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='backend_user',
            field=models.OneToOneField(blank=True, db_comment='系统自动维护的 Django staff 账号，用于承载 /agent-admin/ 后台会话。', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='系统桥接账号'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='root_user',
            field=models.OneToOneField(db_comment='该前台用户既是代理后台登录身份，也是伞下数据根节点。', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='users.frontenduser', verbose_name='代理前台会员'),
        ),
    ]
