# Generated by Django 6.0.4 on 2026-05-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_agentprofile_backend_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontenduser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, db_comment='用于统计前台实时在线人数的最近活跃时间', null=True, verbose_name='最近活跃时间'),
        ),
    ]
