# Generated by Django 6.0.4 on 2026-04-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='binding_platform',
            field=models.CharField(blank=True, choices=[('', '—'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook')], db_comment='仅当必做类型为账号绑定时使用', default='', max_length=20, verbose_name='绑定平台'),
        ),
        migrations.AddField(
            model_name='task',
            name='interaction_config',
            field=models.JSONField(blank=True, db_comment='如 target_tweet_url、require_retweet、youtube_proof_link 等', default=dict, verbose_name='交互配置 JSON'),
        ),
        migrations.AddField(
            model_name='task',
            name='interaction_type',
            field=models.CharField(choices=[('none', '无（不按下面规则校验）'), ('account_binding', '账号绑定'), ('follow', '关注'), ('comment', '评论'), ('watch_video', '观看视频'), ('external_vote', '外部网页投票')], db_comment='账号绑定/关注/评论/看视频/外站投票等', default='none', max_length=32, verbose_name='必做任务类型'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_mode',
            field=models.CharField(blank=True, choices=[('user_self_confirm', '用户自行确认完成'), ('profile_link_proof', '简介/频道留指定链接证明'), ('screenshot_review', '上传截图待审核')], db_comment='由业务推导，也可在后台手动改', max_length=32, null=True, verbose_name='校验方式'),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='bound_username',
            field=models.CharField(blank=True, db_comment='如推特 @handle，用于账号绑定类任务', max_length=128, null=True, verbose_name='绑定账号用户名'),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='proof_image',
            field=models.ImageField(blank=True, db_comment='看视频、外站投票等需截图审核时使用', null=True, upload_to='task_applications/proof/%Y/%m/', verbose_name='完成凭证截图'),
        ),
        migrations.AddField(
            model_name='taskapplication',
            name='self_verified_at',
            field=models.DateTimeField(blank=True, db_comment='用户点击验证完成的时间', null=True, verbose_name='用户标记完成时间'),
        ),
    ]
