# Generated by Django 6.0.4 on 2026-04-15 03:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0002_task_interaction_and_application_proof'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-task_list_order', '-created_at'), 'verbose_name': '任务（发布单 / 首页必做卡片）', 'verbose_name_plural': '任务（发布单 / 首页必做卡片）'},
        ),
        migrations.AddField(
            model_name='task',
            name='is_mandatory',
            field=models.BooleanField(db_comment='对应 TaskFlow 卡片右上角红色必做丝带', default=False, verbose_name='首页显示「必做」角标'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_th_coin',
            field=models.DecimalField(blank=True, db_comment='卡片上 +2 TH 等', decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='展示奖励 TH'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_usdt',
            field=models.DecimalField(blank=True, db_comment='卡片上 +0.05 USDT 等，可与 budget 独立', decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='展示奖励 USDT'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_list_order',
            field=models.PositiveIntegerField(db_comment='数值越大越靠前，用于必做任务区排序', default=0, verbose_name='首页列表排序权重'),
        ),
        migrations.AlterField(
            model_name='task',
            name='binding_platform',
            field=models.CharField(blank=True, choices=[('', '—'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('telegram', 'Telegram')], db_comment='仅当必做类型为账号绑定时使用', default='', max_length=20, verbose_name='绑定平台'),
        ),
        migrations.AlterField(
            model_name='task',
            name='interaction_config',
            field=models.JSONField(blank=True, db_comment='如 target_tweet_url、require_retweet、youtube_proof_link、invite_link 等', default=dict, verbose_name='交互配置 JSON'),
        ),
        migrations.AlterField(
            model_name='task',
            name='interaction_type',
            field=models.CharField(choices=[('none', '无（不按下面规则校验）'), ('account_binding', '账号绑定（首页「绑定 Twitter/TikTok…」卡片）'), ('join_community', '加入社群（如 Telegram 入群/频道）'), ('follow', '关注'), ('comment', '评论'), ('watch_video', '观看视频'), ('external_vote', '外部网页投票')], db_comment='账号绑定/关注/评论/看视频/外站投票等', default='none', max_length=32, verbose_name='必做任务类型'),
        ),
    ]
