# Generated by Django 6.0.4 on 2026-04-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0003_taskflow_card_fields'),
        ('users', '0003_telegram_checkin_miniapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField(db_comment='按 Asia/Shanghai 等当前激活时区的日历日', verbose_name='签到日期')),
                ('is_make_up', models.BooleanField(db_comment='补签为 True', default=False, verbose_name='是否补签')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='写入时间', verbose_name='记录时间')),
                (
                    'user',
                    models.ForeignKey(
                        db_comment='签到用户',
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='check_ins',
                        to='users.frontenduser',
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '每日签到',
                'verbose_name_plural': '每日签到',
                'db_table': 'task_check_in',
                'ordering': ('-on_date', '-id'),
                'unique_together': {('user', 'on_date')},
            },
        ),
    ]
