# Generated by Django 6.0.4 on 2026-04-15 07:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0004_telegram_checkin_miniapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_reward_usdt', models.DecimalField(db_comment='成功签到一次增加的 USDT（可为 0）', decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='每日签到奖励 USDT')),
                ('daily_reward_th_coin', models.DecimalField(db_comment='成功签到一次增加的 TH Coin（可为 0）', decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='每日签到奖励 TH Coin')),
                ('makeup_cost_th_coin', models.DecimalField(db_comment='每次补签从 TH Coin 扣除的数量；为 0 表示不消耗', decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='补签消耗 TH Coin')),
                ('weekly_makeup_limit', models.PositiveIntegerField(db_comment='自然周内最多允许补签次数', default=3, verbose_name='每周补签次数上限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '签到参数配置',
                'verbose_name_plural': '签到参数配置',
                'db_table': 'task_check_in_config',
            },
        ),
    ]
