# Generated by Django 6.0.4 on 2026-04-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0005_checkin_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapplication',
            name='reward_paid_at',
            field=models.DateTimeField(blank=True, db_comment='按任务 reward_usdt/reward_th_coin 入账后写入，防重复发奖', null=True, verbose_name='任务奖励已发放时间'),
        ),
    ]
