# Generated by Django 6.0.4 on 2026-04-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0008_integration_secret_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCompletionRecord',
            fields=[
            ],
            options={
                'verbose_name': '任务完成记录',
                'verbose_name_plural': '任务完成记录',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('taskhub.taskapplication',),
        ),
    ]
