# Generated by Django 6.0.4 on 2026-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0009_task_completion_record_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramStartInvitePending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram 用户 ID')),
                ('start_payload', models.CharField(db_comment='与 deep link ?start= 一致，最长 64', max_length=64, verbose_name='start 参数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Telegram /start 待绑定邀请',
                'verbose_name_plural': 'Telegram /start 待绑定邀请',
                'db_table': 'taskhub_telegram_start_invite_pending',
            },
        ),
    ]
