# Generated by Django 6.0.4 on 2026-04-22 06:26

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def seed_invite_achievement_tiers(apps, schema_editor):
    InviteAchievementTier = apps.get_model("taskhub", "InviteAchievementTier")
    if InviteAchievementTier.objects.exists():
        return
    zero_usdt = Decimal("0")
    zero_th = Decimal("0")
    # 运营可在后台改标题与奖励；此处仅插入默认阈值阶梯
    defaults = [
        (10, 5),
        (20, 10),
        (30, 20),
        (40, 50),
        (50, 100),
        (60, 200),
    ]
    for sort_order, threshold in defaults:
        InviteAchievementTier.objects.create(
            sort_order=sort_order,
            invite_threshold=threshold,
            title="推荐专家",
            reward_usdt=zero_usdt,
            reward_th=zero_th,
            is_active=True,
        )


def seed_invite_achievement_tiers_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0010_telegram_start_invite_pending'),
        ('users', '0004_alter_frontenduser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteAchievementTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_comment='列表展示顺序，越小越靠前', default=0, verbose_name='排序')),
                ('invite_threshold', models.PositiveIntegerField(db_comment='有效直邀人数达到该值可领', verbose_name='需邀请人数')),
                ('title', models.CharField(default='推荐专家', max_length=64, verbose_name='成就标题')),
                ('reward_usdt', models.DecimalField(db_comment='领取时入账钱包 USDT；可为 0', decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='奖励 USDT')),
                ('reward_th', models.DecimalField(db_comment='领取时入账 TH；可为 0', decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='奖励 TH Coin')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邀请成就阶梯',
                'verbose_name_plural': '邀请成就阶梯',
                'db_table': 'task_invite_achievement_tier',
                'ordering': ('sort_order', 'invite_threshold', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InviteAchievementClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='invite_achievement_claims', to='users.frontenduser', verbose_name='用户')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='taskhub.inviteachievementtier', verbose_name='阶梯')),
            ],
            options={
                'verbose_name': '邀请成就领取记录',
                'verbose_name_plural': '邀请成就领取记录',
                'db_table': 'task_invite_achievement_claim',
                'ordering': ('-claimed_at',),
                'unique_together': {('user', 'tier')},
            },
        ),
        migrations.RunPython(seed_invite_achievement_tiers, seed_invite_achievement_tiers_reverse),
    ]
