# Generated by Django 6.0.4 on 2026-04-22 06:38

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def seed_daily_task_definitions(apps, schema_editor):
    DailyTaskDefinition = apps.get_model("taskhub", "DailyTaskDefinition")
    if DailyTaskDefinition.objects.exists():
        return
    z = Decimal("0")
    DailyTaskDefinition.objects.create(
        sort_order=10,
        title="完成 3 个任务",
        metric_code="platform_tasks_done_today",
        target_count=3,
        reward_usdt=z,
        reward_th=z,
        is_active=True,
    )
    DailyTaskDefinition.objects.create(
        sort_order=20,
        title="完成 10 个任务",
        metric_code="platform_tasks_done_today",
        target_count=10,
        reward_usdt=z,
        reward_th=z,
        is_active=True,
    )


def seed_daily_task_definitions_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0011_invite_achievement_tiers'),
        ('users', '0004_alter_frontenduser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_comment='列表顺序，越小越靠前', default=0, verbose_name='排序')),
                ('title', models.CharField(db_comment='如「完成 3 个任务」', max_length=128, verbose_name='任务标题')),
                ('metric_code', models.CharField(choices=[('platform_tasks_done_today', '当日完成任务数（已录用且已完结：已发奖或无展示奖励且已录用）')], db_comment='决定 progress_current 如何计算', default='platform_tasks_done_today', max_length=64, verbose_name='统计口径')),
                ('target_count', models.PositiveIntegerField(db_comment='当日进度达到该值可领取', default=1, verbose_name='目标数量')),
                ('reward_usdt', models.DecimalField(db_comment='领取时入账；可为 0', decimal_places=4, default=Decimal('0'), max_digits=12, verbose_name='奖励 USDT')),
                ('reward_th', models.DecimalField(db_comment='领取时入账 frozen；可为 0', decimal_places=2, default=Decimal('0'), max_digits=20, verbose_name='奖励 TH Coin')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日任务配置',
                'verbose_name_plural': '每日任务配置',
                'db_table': 'task_daily_task_definition',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DailyTaskDayClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_date', models.DateField(db_comment='按当前激活时区的日历日', verbose_name='归属日期')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='领取时间')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='daily_task_day_claims', to='users.frontenduser', verbose_name='用户')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_claims', to='taskhub.dailytaskdefinition', verbose_name='每日任务')),
            ],
            options={
                'verbose_name': '每日任务领取记录',
                'verbose_name_plural': '每日任务领取记录',
                'db_table': 'task_daily_task_day_claim',
                'ordering': ('-on_date', '-id'),
                'unique_together': {('user', 'definition', 'on_date')},
            },
        ),
        migrations.RunPython(seed_daily_task_definitions, seed_daily_task_definitions_reverse),
    ]
