# Generated by Django 6.0.4 on 2026-04-24 03:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0012_daily_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_invite_rate', models.DecimalField(db_comment='下级完成任务后，按其实际到账 USDT 任务奖励乘以该比例给上级发放推荐奖励；0.10 = 10%', decimal_places=4, default=Decimal('0.10'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='直推返佣比例')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '邀请返佣配置',
                'verbose_name_plural': '邀请返佣配置',
                'db_table': 'task_referral_reward_config',
            },
        ),
    ]
