# Generated by Django 6.0.4 on 2026-04-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0013_referralrewardconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='binding_platform',
            field=models.CharField(blank=True, choices=[('', '—'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('telegram', 'Telegram')], db_comment='账号绑定 / 关注 / 点赞类任务使用；决定前台图标与平台校验文案', default='', max_length=20, verbose_name='目标平台'),
        ),
        migrations.AlterField(
            model_name='task',
            name='interaction_type',
            field=models.CharField(choices=[('none', '无（不按下面规则校验）'), ('account_binding', '账号绑定（首页「绑定 Twitter/TikTok…」卡片）'), ('join_community', '加入社群（如 Telegram 入群/频道）'), ('follow', '关注'), ('like', '点赞'), ('comment', '评论'), ('watch_video', '观看视频'), ('external_vote', '外部网页投票')], db_comment='账号绑定/关注/评论/看视频/外站投票等', default='none', max_length=32, verbose_name='必做任务类型'),
        ),
    ]
