# Generated by Codex on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskhub", "0014_alter_task_binding_platform_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("none", "无（不按下面规则校验）"),
                    ("account_binding", "账号绑定（首页「绑定 Twitter/TikTok…」卡片）"),
                    ("join_community", "加入社群（如 Telegram 入群/频道）"),
                    ("follow", "关注"),
                    ("like", "点赞"),
                    ("comment", "评论"),
                    ("watch_video", "观看视频"),
                    ("external_vote", "外部网页投票"),
                    ("screenshot_proof", "上传截图审核"),
                ],
                db_comment="账号绑定/关注/评论/看视频/外站投票等",
                default="none",
                max_length=32,
                verbose_name="必做任务类型",
            ),
        ),
    ]
