# Generated by Codex on 2026-04-25

from decimal import Decimal

from django.conf import settings
from django.db import migrations


def seed_screenshot_proof_test_task(apps, schema_editor):
    FrontendUser = apps.get_model("users", "FrontendUser")
    Task = apps.get_model("taskhub", "Task")
    TaskCategory = apps.get_model("taskhub", "TaskCategory")

    publisher_id = getattr(settings, "TASK_PLATFORM_PUBLISHER_ID", None)
    if publisher_id is None:
        return
    publisher = FrontendUser.objects.filter(pk=int(publisher_id)).first()
    if publisher is None:
        return

    category, _ = TaskCategory.objects.get_or_create(
        slug="screenshot-proof",
        defaults={
            "name": "截图审核",
            "description": "需要用户上传完成截图，由后台人工审核的任务",
            "sort_order": 80,
            "is_active": True,
        },
    )

    Task.objects.update_or_create(
        title="测试任务：上传截图审核",
        defaults={
            "category": category,
            "publisher": publisher,
            "description": (
                "测试截图审核流程：请打开任意目标页面，按任务要求完成后上传截图。"
                "\n后台可在「任务报名」中查看截图并审核通过或拒绝。"
            ),
            "budget": Decimal("0.00"),
            "reward_unit": "USDT",
            "applicants_limit": 100,
            "status": "open",
            "interaction_type": "screenshot_proof",
            "binding_platform": "",
            "verification_mode": "screenshot_review",
            "interaction_config": {
                "target_url": "https://example.com/",
                "instructions": "完成指定页面操作后，请上传清晰截图，等待后台审核。",
            },
            "is_mandatory": False,
            "task_list_order": 0,
            "reward_usdt": Decimal("0.01"),
            "reward_th_coin": Decimal("0.10"),
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("taskhub", "0015_screenshot_proof_interaction"),
    ]

    operations = [
        migrations.RunPython(seed_screenshot_proof_test_task, migrations.RunPython.noop),
    ]
