# Generated by Django 6.0.4 on 2026-04-26 08:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def seed_invite_activity_rules(apps, schema_editor):
    ReferralRewardConfig = apps.get_model("taskhub", "ReferralRewardConfig")
    MembershipLevelConfig = apps.get_model("taskhub", "MembershipLevelConfig")
    TeamLeaderTier = apps.get_model("taskhub", "TeamLeaderTier")

    config = ReferralRewardConfig.objects.order_by("id").first()
    if config is None:
        config = ReferralRewardConfig.objects.create()
    config.activity_title = "关于任务邀请好友拉新活动会员等级"
    config.activity_intro = "邀请好友加入 TaskHub，完成任务、充值会员与团队成长都可按后台配置获得奖励。"
    if config.direct_invite_rate == Decimal("0.10"):
        config.direct_invite_rate = Decimal("0.20")
    config.second_task_rate = Decimal("0.10")
    config.direct_recharge_rate = Decimal("0.10")
    config.second_recharge_rate = Decimal("0.05")
    config.save(
        update_fields=[
            "activity_title",
            "activity_intro",
            "direct_invite_rate",
            "second_task_rate",
            "direct_recharge_rate",
            "second_recharge_rate",
            "updated_at",
        ]
    )

    membership_rows = [
        {
            "level": 0,
            "name": "VIP0",
            "join_fee_usdt": Decimal("0.00"),
            "can_claim_free_tasks": True,
            "can_claim_official_tasks": False,
            "can_claim_high_commission_tasks": False,
            "daily_official_task_limit": None,
            "unlimited_tasks": False,
            "withdraw_fee_rate": Decimal("0.20"),
            "description": "加入费用 0 USDT；只能领取免费任务；提现手续费 20%。",
            "sort_order": 0,
        },
        {
            "level": 1,
            "name": "VIP1",
            "join_fee_usdt": Decimal("50.00"),
            "can_claim_free_tasks": True,
            "can_claim_official_tasks": True,
            "can_claim_high_commission_tasks": False,
            "daily_official_task_limit": 1,
            "unlimited_tasks": False,
            "withdraw_fee_rate": Decimal("0.10"),
            "description": "费用 50 USDT；可以领取官方发布任务；一天领取数量 1 笔；提现手续费 10%。",
            "sort_order": 1,
        },
        {
            "level": 2,
            "name": "VIP2",
            "join_fee_usdt": Decimal("100.00"),
            "can_claim_free_tasks": True,
            "can_claim_official_tasks": True,
            "can_claim_high_commission_tasks": True,
            "daily_official_task_limit": 2,
            "unlimited_tasks": False,
            "withdraw_fee_rate": Decimal("0.05"),
            "description": "费用 100 USDT；可以领取官方任务；一天领取数量 2 笔；可领取佣金更高的任务；提现手续费 5%。",
            "sort_order": 2,
        },
        {
            "level": 3,
            "name": "VIP3",
            "join_fee_usdt": Decimal("1000.00"),
            "can_claim_free_tasks": True,
            "can_claim_official_tasks": True,
            "can_claim_high_commission_tasks": True,
            "daily_official_task_limit": None,
            "unlimited_tasks": True,
            "withdraw_fee_rate": Decimal("0.00"),
            "description": "费用 1000 USDT；不限制任务，只要平台任务都可以做；提现手续费 0%。",
            "sort_order": 3,
        },
    ]
    for row in membership_rows:
        level = row.pop("level")
        MembershipLevelConfig.objects.update_or_create(level=level, defaults={**row, "is_active": True})

    tier_rows = [
        {
            "name": "初级代理",
            "direct_vip_count": 10,
            "team_recharge_target_usdt": Decimal("2000.00"),
            "target_period": "cumulative",
            "team_performance_rate": Decimal("0.02"),
            "description": "直推 10 个 VIP，累计团队充值业绩达到 2,000 USDT，额外团队业绩提成 2%。",
            "sort_order": 0,
        },
        {
            "name": "中级合伙人",
            "direct_vip_count": 30,
            "team_recharge_target_usdt": Decimal("10000.00"),
            "target_period": "monthly",
            "team_performance_rate": Decimal("0.05"),
            "description": "直推 30 个 VIP，每月团队充值业绩达到 10,000 USDT，额外团队业绩提成 5%。",
            "sort_order": 1,
        },
        {
            "name": "顶级领袖",
            "direct_vip_count": 100,
            "team_recharge_target_usdt": Decimal("50000.00"),
            "target_period": "monthly",
            "team_performance_rate": Decimal("0.10"),
            "description": "直推 100 个 VIP，每月团队充值业绩达到 50,000 USDT，额外团队业绩提成 10%。",
            "sort_order": 2,
        },
    ]
    for row in tier_rows:
        TeamLeaderTier.objects.update_or_create(name=row["name"], defaults={**row, "is_active": True})


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0016_seed_screenshot_proof_test_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipLevelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(db_comment='与 FrontendUser.membership_level 对应，例如 0=VIP0，1=VIP1', unique=True, verbose_name='等级数值')),
                ('name', models.CharField(db_comment='如 VIP0 / VIP1', max_length=32, verbose_name='等级名称')),
                ('join_fee_usdt', models.DecimalField(db_comment='升级/加入该等级所需 USDT；0 表示免费', decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='加入费用 USDT')),
                ('can_claim_free_tasks', models.BooleanField(default=True, verbose_name='可领取免费任务')),
                ('can_claim_official_tasks', models.BooleanField(default=False, verbose_name='可领取官方发布任务')),
                ('can_claim_high_commission_tasks', models.BooleanField(default=False, verbose_name='可领取高佣金任务')),
                ('daily_official_task_limit', models.PositiveIntegerField(blank=True, db_comment='留空表示不限量；VIP1 可填 1，VIP2 可填 2', null=True, verbose_name='每日官方任务领取上限')),
                ('unlimited_tasks', models.BooleanField(default=False, verbose_name='不限任务')),
                ('withdraw_fee_rate', models.DecimalField(db_comment='0.20 = 提现金额的 20 percent；0 = 不收手续费', decimal_places=4, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='提现手续费比例')),
                ('description', models.TextField(blank=True, default='', verbose_name='等级说明')),
                ('sort_order', models.PositiveIntegerField(db_comment='越小越靠前', default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会员等级活动配置',
                'verbose_name_plural': '会员等级活动配置',
                'db_table': 'task_membership_level_config',
                'ordering': ('sort_order', 'level'),
            },
        ),
        migrations.CreateModel(
            name='TeamLeaderTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_comment='越小越靠前', default=0, verbose_name='排序')),
                ('name', models.CharField(db_comment='如 初级代理 / 中级合伙人', max_length=64, verbose_name='等级名称')),
                ('direct_vip_count', models.PositiveIntegerField(db_comment='达到该直推 VIP 人数后满足人数门槛', default=0, verbose_name='直推 VIP 人数门槛')),
                ('team_recharge_target_usdt', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='团队总充值业绩目标 USDT')),
                ('target_period', models.CharField(choices=[('cumulative', '累计'), ('monthly', '每月')], db_comment='累计或每月', default='cumulative', max_length=16, verbose_name='业绩周期')),
                ('team_performance_rate', models.DecimalField(db_comment='0.02 = 2 percent', decimal_places=4, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='额外团队业绩提成比例')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队长扶持阶梯',
                'verbose_name_plural': '团队长扶持阶梯',
                'db_table': 'task_team_leader_tier',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='referralrewardconfig',
            name='activity_intro',
            field=models.TextField(blank=True, db_comment='前台/机器人展示的活动简介，可按运营口径修改', default='邀请好友加入 TaskHub，完成任务、充值会员与团队成长都可按后台配置获得奖励。', verbose_name='活动简介'),
        ),
        migrations.AddField(
            model_name='referralrewardconfig',
            name='activity_title',
            field=models.CharField(db_comment='前台/机器人展示的邀请拉新活动标题', default='关于任务邀请好友拉新活动会员等级', max_length=128, verbose_name='活动标题'),
        ),
        migrations.AddField(
            model_name='referralrewardconfig',
            name='direct_recharge_rate',
            field=models.DecimalField(db_comment='一级下级充值后，按充值 USDT 金额乘以该比例给上级发放奖励；0.10 = 10 percent', decimal_places=4, default=Decimal('0.10'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='一级充值佣金比例'),
        ),
        migrations.AddField(
            model_name='referralrewardconfig',
            name='second_recharge_rate',
            field=models.DecimalField(db_comment='二级下级充值后，按充值 USDT 金额乘以该比例给上二级发放奖励；0.05 = 5 percent', decimal_places=4, default=Decimal('0.05'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='二级充值佣金比例'),
        ),
        migrations.AddField(
            model_name='referralrewardconfig',
            name='second_task_rate',
            field=models.DecimalField(db_comment='二级下级完成任务后，按其实际到账 USDT 任务奖励乘以该比例给上二级发放奖励；0.10 = 10 percent', decimal_places=4, default=Decimal('0.10'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='二级任务分成比例'),
        ),
        migrations.AlterField(
            model_name='referralrewardconfig',
            name='direct_invite_rate',
            field=models.DecimalField(db_comment='一级下级完成任务后，按其实际到账 USDT 任务奖励乘以该比例给上级发放推荐奖励；0.20 = 20 percent', decimal_places=4, default=Decimal('0.20'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='一级任务分成比例'),
        ),
        migrations.RunPython(seed_invite_activity_rules, migrations.RunPython.noop),
    ]
