# Generated by Django 6.0.4 on 2026-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0018_alter_task_interaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_vip_exclusive',
            field=models.BooleanField(db_comment='勾选后仅在前台 VIP 任务专区展示，并按会员等级限制每日可接次数', default=False, verbose_name='VIP 任务专区'),
        ),
        migrations.AlterField(
            model_name='membershiplevelconfig',
            name='can_claim_official_tasks',
            field=models.BooleanField(default=False, verbose_name='可领取 VIP 任务专区'),
        ),
        migrations.AlterField(
            model_name='membershiplevelconfig',
            name='daily_official_task_limit',
            field=models.PositiveIntegerField(blank=True, db_comment='留空表示不限量；VIP1 可填 1，VIP2 可填 2，VIP3 可不限量', null=True, verbose_name='每日 VIP 任务领取上限'),
        ),
        migrations.AlterField(
            model_name='membershiplevelconfig',
            name='unlimited_tasks',
            field=models.BooleanField(default=False, verbose_name='VIP任务不限量'),
        ),
    ]
