# Generated by Django 6.0.4 on 2026-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskhub", "0019_task_is_vip_exclusive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_auth_token",
            field=models.TextField(
                blank=True,
                db_comment="用于 Apify 关注校验；留空则使用 Actor 默认或 settings / 环境变量",
                default="",
                verbose_name="Twitter auth_token Cookie",
            ),
        ),
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_ct0",
            field=models.TextField(
                blank=True,
                db_comment="用于 Apify 关注校验；留空则使用 Actor 默认或 settings / 环境变量",
                default="",
                verbose_name="Twitter ct0 Cookie",
            ),
        ),
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_follow_actor_id",
            field=models.CharField(
                blank=True,
                db_comment="默认 scraperx/twitter-user-following-scraper",
                default="",
                max_length=256,
                verbose_name="Apify Twitter 关注 Actor ID",
            ),
        ),
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_following_max_results",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="用于从 following 列表中查找目标账号，留空则使用 settings / 环境变量",
                null=True,
                verbose_name="Twitter 关注校验最大抓取数",
            ),
        ),
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_repost_actor_id",
            field=models.CharField(
                blank=True,
                db_comment="默认 api-ninja/x-twitter-replies-retweets-scraper",
                default="",
                max_length=256,
                verbose_name="Apify Twitter 转发 Actor ID",
            ),
        ),
        migrations.AddField(
            model_name="integrationsecretconfig",
            name="apify_twitter_timeout_sec",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="留空则使用 settings / 环境变量",
                null=True,
                verbose_name="Twitter 请求超时（秒）",
            ),
        ),
    ]
