# Generated by Django 6.0.4 on 2026-05-01 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0021_task_virtual_application_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='virtual_auto_increment_count',
            field=models.PositiveIntegerField(db_comment='系统按小时自动累加的虚拟参与人数', default=0, editable=False, verbose_name='自动增长累计人数'),
        ),
        migrations.AddField(
            model_name='task',
            name='virtual_growth_last_at',
            field=models.DateTimeField(blank=True, db_comment='系统最近一次结算虚拟参与人数增长的时间', editable=False, null=True, verbose_name='虚拟增长上次结算时间'),
        ),
        migrations.AddField(
            model_name='task',
            name='virtual_hourly_growth_max',
            field=models.PositiveIntegerField(db_comment='启用自动增长后，每整小时随机增加的最大人数；需大于等于最小值', default=0, verbose_name='每小时虚拟增长最大值'),
        ),
        migrations.AddField(
            model_name='task',
            name='virtual_hourly_growth_min',
            field=models.PositiveIntegerField(db_comment='启用自动增长后，每整小时随机增加的最小人数；0 表示不启用', default=0, verbose_name='每小时虚拟增长最小值'),
        ),
        migrations.AlterField(
            model_name='task',
            name='virtual_application_count',
            field=models.PositiveIntegerField(db_comment='基础虚拟参与人数，仅用于前台任务列表展示，会叠加真实报名数与自动增长数', default=0, verbose_name='虚拟参与人数'),
        ),
    ]
