# Generated by Django 6.0.4 on 2026-05-04 16:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0022_task_virtual_auto_increment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformStatsDisplayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_virtual_base', models.PositiveIntegerField(db_comment='叠加到真实任务总数上的基础虚拟值', default=0, verbose_name='任务总数虚拟基础值')),
                ('total_tasks_hourly_growth_min', models.PositiveIntegerField(db_comment='每整小时随机增加的最小任务总数虚拟值', default=0, verbose_name='任务总数每小时增长最小值')),
                ('total_tasks_hourly_growth_max', models.PositiveIntegerField(db_comment='每整小时随机增加的最大任务总数虚拟值', default=0, verbose_name='任务总数每小时增长最大值')),
                ('total_tasks_virtual_auto_increment', models.PositiveIntegerField(db_comment='系统按小时累计增长的任务总数虚拟值', default=0, editable=False, verbose_name='任务总数自动增长累计值')),
                ('total_rewards_usdt_virtual_base', models.DecimalField(db_comment='叠加到真实总发放奖励上的基础虚拟值', decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='总发放奖励虚拟基础值（USDT）')),
                ('total_rewards_usdt_hourly_growth_min', models.DecimalField(db_comment='每整小时随机增加的最小总发放奖励虚拟值', decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='总发放奖励每小时增长最小值（USDT）')),
                ('total_rewards_usdt_hourly_growth_max', models.DecimalField(db_comment='每整小时随机增加的最大总发放奖励虚拟值', decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='总发放奖励每小时增长最大值（USDT）')),
                ('total_rewards_usdt_virtual_auto_increment', models.DecimalField(db_comment='系统按小时累计增长的总发放奖励虚拟值', decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='总发放奖励自动增长累计值（USDT）')),
                ('total_users_virtual_base', models.PositiveIntegerField(db_comment='叠加到真实总用户数上的基础虚拟值', default=0, verbose_name='总用户数虚拟基础值')),
                ('total_users_hourly_growth_min', models.PositiveIntegerField(db_comment='每整小时随机增加的最小总用户数虚拟值', default=0, verbose_name='总用户数每小时增长最小值')),
                ('total_users_hourly_growth_max', models.PositiveIntegerField(db_comment='每整小时随机增加的最大总用户数虚拟值', default=0, verbose_name='总用户数每小时增长最大值')),
                ('total_users_virtual_auto_increment', models.PositiveIntegerField(db_comment='系统按小时累计增长的总用户数虚拟值', default=0, editable=False, verbose_name='总用户数自动增长累计值')),
                ('online_users_virtual_base', models.PositiveIntegerField(db_comment='排行页在线人数为纯展示字段，取基础值叠加自动增长值', default=0, verbose_name='在线人数虚拟基础值')),
                ('online_users_hourly_growth_min', models.PositiveIntegerField(db_comment='每整小时随机增加的最小在线人数虚拟值', default=0, verbose_name='在线人数每小时增长最小值')),
                ('online_users_hourly_growth_max', models.PositiveIntegerField(db_comment='每整小时随机增加的最大在线人数虚拟值', default=0, verbose_name='在线人数每小时增长最大值')),
                ('online_users_virtual_auto_increment', models.PositiveIntegerField(db_comment='系统按小时累计增长的在线人数虚拟值', default=0, editable=False, verbose_name='在线人数自动增长累计值')),
                ('operating_days_virtual_base', models.PositiveIntegerField(db_comment='叠加到真实运营天数上的基础虚拟值', default=0, verbose_name='运营天数虚拟基础值')),
                ('operating_days_hourly_growth_min', models.PositiveIntegerField(db_comment='每整小时随机增加的最小运营天数虚拟值', default=0, verbose_name='运营天数每小时增长最小值')),
                ('operating_days_hourly_growth_max', models.PositiveIntegerField(db_comment='每整小时随机增加的最大运营天数虚拟值', default=0, verbose_name='运营天数每小时增长最大值')),
                ('operating_days_virtual_auto_increment', models.PositiveIntegerField(db_comment='系统按小时累计增长的运营天数虚拟值', default=0, editable=False, verbose_name='运营天数自动增长累计值')),
                ('virtual_growth_last_at', models.DateTimeField(blank=True, db_comment='系统最近一次按小时结算统计虚拟增长的时间', editable=False, null=True, verbose_name='统计虚拟增长上次结算时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '首页统计虚拟参数',
                'verbose_name_plural': '首页统计虚拟参数',
                'db_table': 'task_platform_stats_display_config',
            },
        ),
    ]
