# Generated by Django 6.0.4 on 2026-05-05 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0023_platformstatsdisplayconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformstatsdisplayconfig',
            options={'verbose_name': '首页排行榜统计配置', 'verbose_name_plural': '首页排行榜统计配置'},
        ),
        migrations.RemoveField(
            model_name='platformstatsdisplayconfig',
            name='online_users_hourly_growth_max',
        ),
        migrations.RemoveField(
            model_name='platformstatsdisplayconfig',
            name='online_users_hourly_growth_min',
        ),
        migrations.RemoveField(
            model_name='platformstatsdisplayconfig',
            name='online_users_virtual_auto_increment',
        ),
        migrations.RemoveField(
            model_name='platformstatsdisplayconfig',
            name='online_users_virtual_base',
        ),
    ]
