# Generated by Django 6.0.4 on 2026-05-05 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub', '0025_screenshotproofreview_proxy'),
        ('users', '0008_frontenduser_last_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='用户填写的反馈标题', max_length=120, verbose_name='反馈标题')),
                ('content', models.TextField(db_comment='用户填写的反馈详细内容', verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, db_comment='用户可选填写的联系方式', default='', max_length=120, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待回复'), ('replied', '已回复'), ('closed', '已关闭')], db_comment='反馈处理状态', default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_reply', models.TextField(blank=True, db_comment='后台给用户的回复内容', default='', verbose_name='后台回复')),
                ('replied_by', models.CharField(blank=True, db_comment='后台回复人的显示名', default='', max_length=120, verbose_name='回复人')),
                ('replied_at', models.DateTimeField(blank=True, db_comment='后台回复时间', null=True, verbose_name='回复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='反馈提交时间', verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='最后更新时间', verbose_name='更新时间')),
                ('user', models.ForeignKey(db_comment='提交反馈的前台用户', on_delete=django.db.models.deletion.CASCADE, related_name='online_feedbacks', to='users.frontenduser', verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '在线反馈',
                'verbose_name_plural': '在线反馈',
                'db_table': 'task_online_feedback',
                'ordering': ('-updated_at', '-id'),
            },
        ),
    ]
