# Generated by Django 6.0.4 on 2026-04-09 09:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(db_comment='用户当前可提现或消费的真实余额', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='可用余额')),
                ('frozen', models.DecimalField(db_comment='提现审核中被锁定的金额', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='冻结金额')),
                ('user', models.OneToOneField(db_comment='关联的前台用户ID', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='users.frontenduser', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
                'db_table': 'frontend_wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(db_comment='本次账变金额，正数增加，负数减少', decimal_places=2, max_digits=20, verbose_name='变动金额')),
                ('before_balance', models.DecimalField(db_comment='变动前的钱包余额', decimal_places=2, max_digits=20, verbose_name='变动前')),
                ('after_balance', models.DecimalField(db_comment='变动后的钱包余额', decimal_places=2, max_digits=20, verbose_name='变动后')),
                ('change_type', models.CharField(choices=[('recharge', '充值'), ('withdraw', '提现'), ('reward', '推荐奖励'), ('cost', '消费')], db_comment='业务类型：充值、提现等', max_length=20, verbose_name='账变类型')),
                ('remark', models.CharField(blank=True, db_comment='账变具体说明', max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='账变发生的时间', verbose_name='时间')),
                ('wallet', models.ForeignKey(db_comment='发生账变的钱包ID', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='wallets.wallet', verbose_name='所属钱包')),
            ],
            options={
                'verbose_name': '账变记录',
                'verbose_name_plural': '账变记录',
                'db_table': 'frontend_transaction',
            },
        ),
    ]
