# Generated by Django 6.0.4 on 2026-04-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='change_type',
            field=models.CharField(choices=[('recharge', '充值'), ('withdraw', '提现'), ('reward', '推荐奖励'), ('cost', '消费'), ('adjust', '调账'), ('admin_adjust', '后台拨币')], db_comment='业务类型：充值、提现等', max_length=20, verbose_name='账变类型'),
        ),
    ]
