# Generated by Django 6.0.4 on 2026-04-15 06:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_expand_transaction_change_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(db_comment='用户当前可提现或消费的 USDT 余额', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='USDT'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='frozen',
            field=models.DecimalField(db_comment='TH Coin 数量（含冻结/锁定场景）', decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='TH Coin'),
        ),
    ]
