# Generated by Django 6.0.4 on 2026-04-15 07:51

from django.db import migrations, models


def backfill_checkin_change_types(apps, schema_editor):
    Tx = apps.get_model("wallets", "Transaction")
    for t in Tx.objects.iterator():
        r = t.remark or ""
        if "补签消耗" in r:
            new_ct = "check_in_makeup_cost"
        elif "补签奖励" in r:
            new_ct = "check_in_makeup"
        elif "每日签到" in r:
            new_ct = "check_in"
        else:
            continue
        if t.change_type != new_ct:
            t.change_type = new_ct
            t.save(update_fields=["change_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_usdt_th_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='change_type',
            field=models.CharField(choices=[('recharge', '充值'), ('withdraw', '提现'), ('reward', '推荐奖励'), ('cost', '消费'), ('adjust', '调账'), ('admin_adjust', '后台拨币'), ('check_in', '每日签到'), ('check_in_makeup', '补签奖励'), ('check_in_makeup_cost', '补签消耗')], db_comment='业务类型：充值、提现等', max_length=20, verbose_name='账变类型'),
        ),
        migrations.RunPython(backfill_checkin_change_types, migrations.RunPython.noop),
    ]
