# Generated by Django 6.0.4 on 2026-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_withdrawal_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='change_type',
            field=models.CharField(choices=[('recharge', '充值'), ('withdraw', '提现'), ('reward', '推荐奖励'), ('task_reward', '任务奖励'), ('cost', '消费'), ('adjust', '调账'), ('admin_adjust', '后台拨币'), ('check_in', '每日签到'), ('check_in_makeup', '补签奖励'), ('check_in_makeup_cost', '补签消耗'), ('invite_achievement', '邀请成就奖励'), ('daily_task', '每日任务奖励')], db_comment='业务类型：充值、提现等', max_length=20, verbose_name='账变类型'),
        ),
    ]
