# Generated by Django 6.0.4 on 2026-04-23 07:04

from django.db import migrations, models


def backfill_transaction_asset(apps, schema_editor):
    Transaction = apps.get_model("wallets", "Transaction")
    Transaction.objects.filter(remark__icontains="TH Coin").update(asset="th_coin")
    Transaction.objects.filter(remark__icontains="冻结").update(asset="th_coin")


def reset_transaction_asset(apps, schema_editor):
    Transaction = apps.get_model("wallets", "Transaction")
    Transaction.objects.update(asset="usdt")


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_alter_transaction_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='asset',
            field=models.CharField(choices=[('usdt', 'USDT'), ('th_coin', 'TH Coin')], db_comment='账变归属资产：USDT 或 TH Coin，用于前台分开展示明细', db_index=True, default='usdt', max_length=16, verbose_name='资产'),
        ),
        migrations.RunPython(backfill_transaction_asset, reset_transaction_asset),
    ]
