# Generated by Django 6.0.4 on 2026-04-26 09:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_recharge_networks(apps, schema_editor):
    RechargeNetworkConfig = apps.get_model("wallets", "RechargeNetworkConfig")
    rows = [
        ("TRC20", "USDT-TRC20", 0, "请使用 TRON/TRC20 网络充值 USDT，提交后等待后台审核入账。"),
        ("ERC20", "USDT-ERC20", 1, "请使用 Ethereum/ERC20 网络充值 USDT，注意链上手续费较高。"),
        ("BEP20", "USDT-BEP20", 2, "请使用 BNB Smart Chain/BEP20 网络充值 USDT。"),
    ]
    for chain, display_name, sort_order, instructions in rows:
        RechargeNetworkConfig.objects.update_or_create(
            chain=chain,
            defaults={
                "display_name": display_name,
                "sort_order": sort_order,
                "min_amount_usdt": Decimal("1.00"),
                "confirmations_required": 1,
                "is_active": True,
                "instructions": instructions,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_agentprofile_backend_user_and_more'),
        ('wallets', '0008_transaction_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechargeNetworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20'), ('BEP20', 'BEP20')], max_length=16, unique=True, verbose_name='充值网络')),
                ('display_name', models.CharField(db_comment='如 USDT-TRC20', max_length=64, verbose_name='展示名称')),
                ('deposit_address', models.CharField(blank=True, db_comment='用户充值时展示的 USDT 收款地址；可先留空，配置后再开放', default='', max_length=160, verbose_name='平台收款地址')),
                ('min_amount_usdt', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='最低充值 USDT')),
                ('confirmations_required', models.PositiveSmallIntegerField(default=1, verbose_name='确认数要求')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('instructions', models.TextField(blank=True, default='', verbose_name='充值说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '充值网络配置',
                'verbose_name_plural': '充值网络配置',
                'db_table': 'wallet_recharge_network_config',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RechargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='充值金额 USDT')),
                ('chain', models.CharField(choices=[('TRC20', 'TRC20'), ('ERC20', 'ERC20'), ('BEP20', 'BEP20')], max_length=16, verbose_name='充值网络')),
                ('deposit_address', models.CharField(blank=True, db_comment='用户提交时平台展示的地址快照', default='', max_length=160, verbose_name='收款地址快照')),
                ('from_address', models.CharField(blank=True, default='', max_length=160, verbose_name='付款地址')),
                ('tx_hash', models.CharField(max_length=160, verbose_name='交易哈希 TxHash')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('completed', '已入账'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='拒绝原因')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('credited_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_requests', to='wallets.transaction', verbose_name='入账账变')),
                ('user', models.ForeignKey(db_comment='提交充值的前台用户', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='users.frontenduser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值申请',
                'verbose_name_plural': '充值申请',
                'db_table': 'wallet_recharge_request',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('chain', 'tx_hash'), name='uniq_recharge_chain_tx_hash')],
            },
        ),
        migrations.RunPython(seed_recharge_networks, migrations.RunPython.noop),
    ]
