# Generated by Django 6.0.4 on 2026-04-26 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_agentprofile_backend_user_and_more'),
        ('wallets', '0009_rechargenetworkconfig_rechargerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRechargeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=160, unique=True, verbose_name='充值地址')),
                ('address_hex', models.CharField(blank=True, db_comment='TRON 用于链上接口的 41 前缀 hex；EVM 为 0x 地址', default='', max_length=128, verbose_name='地址 Hex')),
                ('derivation_index', models.PositiveIntegerField(verbose_name='派生序号')),
                ('account_path', models.CharField(max_length=128, verbose_name='派生路径')),
                ('status', models.CharField(choices=[('active', '启用'), ('archived', '归档')], default='active', max_length=16, verbose_name='状态')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发现入账时间')),
                ('last_swept_at', models.DateTimeField(blank=True, null=True, verbose_name='最近归集时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户充值地址',
                'verbose_name_plural': '用户充值地址',
                'db_table': 'wallet_user_recharge_address',
                'ordering': ('network__sort_order', 'user_id', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='rechargerequest',
            name='uniq_recharge_chain_tx_hash',
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='api_key',
            field=models.TextField(blank=True, db_comment='如 TronGrid API Key；留空则按公共节点访问', default='', verbose_name='链上 API Key'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='collector_address',
            field=models.CharField(blank=True, db_comment='链上充值自动归集到的总地址', default='', max_length=160, verbose_name='归集地址'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='collector_private_key',
            field=models.TextField(blank=True, db_comment='用于给充值地址补 Gas 及归集 USDT；建议仅管理员可见', default='', verbose_name='归集/手续费私钥'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='evm_chain_id',
            field=models.PositiveBigIntegerField(blank=True, db_comment='ERC20/BEP20 使用；TRC20 留空', null=True, verbose_name='EVM Chain ID'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='master_mnemonic',
            field=models.TextField(blank=True, db_comment='用于给每个用户派生独立充值地址；请妥善保管', default='', verbose_name='HD 主助记词'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='min_sweep_amount_usdt',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='最小归集 USDT'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='mnemonic_passphrase',
            field=models.CharField(blank=True, db_comment='若助记词无附加密码可留空', default='', max_length=255, verbose_name='助记词附加密码'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='next_derivation_index',
            field=models.PositiveIntegerField(default=0, verbose_name='下一个派生序号'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='rpc_endpoint',
            field=models.CharField(blank=True, db_comment='EVM 填 JSON-RPC；TRON 填 fullnode / TronGrid 根地址', default='', max_length=255, verbose_name='RPC / API 地址'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='scan_from_block',
            field=models.BigIntegerField(blank=True, db_comment='EVM 网络首次扫链的起始块；留空则首次从最近区块回溯', null=True, verbose_name='扫链起始块'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='sweep_enabled',
            field=models.BooleanField(default=True, verbose_name='自动归集'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='token_contract_address',
            field=models.CharField(blank=True, db_comment='ERC20/BEP20/TRC20 对应的 USDT 合约地址', default='', max_length=160, verbose_name='USDT 合约地址'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='token_decimals',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Token 精度'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='token_transfer_gas_limit',
            field=models.PositiveIntegerField(default=100000, verbose_name='Token 转账 Gas Limit'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='topup_native_amount',
            field=models.DecimalField(db_comment='EVM 为 ETH/BNB，TRC20 为 TRX', decimal_places=8, default=Decimal('0.00030000'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='补 Gas 数量'),
        ),
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='tron_fee_limit_sun',
            field=models.PositiveBigIntegerField(default=30000000, verbose_name='TRON Fee Limit (sun)'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='block_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='区块高度'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='confirmations',
            field=models.PositiveIntegerField(default=0, verbose_name='确认数'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='credited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='到账时间'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='最近错误'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='log_index',
            field=models.PositiveIntegerField(default=0, verbose_name='日志序号'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_requests', to='wallets.rechargenetworkconfig', verbose_name='网络配置'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='链上原始载荷'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='source_type',
            field=models.CharField(choices=[('manual_submission', '人工提单（旧版）'), ('chain_auto', '链上自动发现')], default='manual_submission', max_length=20, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='sweep_status',
            field=models.CharField(choices=[('none', '未归集'), ('pending', '归集中'), ('completed', '已归集'), ('failed', '归集失败')], default='none', max_length=20, verbose_name='归集状态'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='sweep_tx_hash',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='归集交易哈希'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='swept_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归集完成时间'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='token_contract_address',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='合约地址'),
        ),
        migrations.AlterField(
            model_name='rechargenetworkconfig',
            name='deposit_address',
            field=models.CharField(blank=True, db_comment='旧版人工提单模式遗留字段；新逻辑使用每个用户的独立充值地址', default='', max_length=160, verbose_name='旧版固定充值地址（已弃用）'),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='deposit_address',
            field=models.CharField(blank=True, db_comment='用户专属充值地址快照', default='', max_length=160, verbose_name='收款地址快照'),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='status',
            field=models.CharField(choices=[('pending', '确认中'), ('completed', '已到账'), ('rejected', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='rechargerequest',
            name='user',
            field=models.ForeignKey(db_comment='该笔链上充值归属的前台用户', on_delete=django.db.models.deletion.CASCADE, related_name='recharge_requests', to='users.frontenduser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='userrechargeaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='wallets.rechargenetworkconfig', verbose_name='充值网络'),
        ),
        migrations.AddField(
            model_name='userrechargeaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_addresses', to='users.frontenduser', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='rechargerequest',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_requests', to='wallets.userrechargeaddress', verbose_name='用户充值地址'),
        ),
        migrations.AddConstraint(
            model_name='rechargerequest',
            constraint=models.UniqueConstraint(fields=('chain', 'tx_hash', 'log_index'), name='uniq_recharge_chain_tx_hash_log'),
        ),
        migrations.AddConstraint(
            model_name='userrechargeaddress',
            constraint=models.UniqueConstraint(fields=('user', 'network'), name='uniq_user_recharge_address'),
        ),
        migrations.AddConstraint(
            model_name='userrechargeaddress',
            constraint=models.UniqueConstraint(fields=('network', 'derivation_index'), name='uniq_network_derivation_index'),
        ),
    ]
