# Generated by Django 6.0.4 on 2026-04-29 10:44

from django.db import migrations, models


def backfill_sweep_destination_address(apps, schema_editor):
    RechargeNetworkConfig = apps.get_model('wallets', 'RechargeNetworkConfig')
    for row in RechargeNetworkConfig.objects.all().iterator():
        if (row.sweep_destination_address or "").strip():
            continue
        row.sweep_destination_address = (row.collector_address or "").strip()
        row.save(update_fields=['sweep_destination_address'])


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_repair_auto_recharge_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargenetworkconfig',
            name='sweep_destination_address',
            field=models.CharField(blank=True, db_comment='用户充值地址里的 USDT 最终归集到的目标地址；无需在系统内保存该地址私钥', default='', max_length=160, verbose_name='归集目标地址'),
        ),
        migrations.AlterField(
            model_name='rechargenetworkconfig',
            name='collector_address',
            field=models.CharField(blank=True, db_comment='用于给用户充值地址补 Gas / TRX 的热钱包地址；需与下方私钥匹配', default='', max_length=160, verbose_name='手续费钱包地址'),
        ),
        migrations.AlterField(
            model_name='rechargenetworkconfig',
            name='collector_private_key',
            field=models.TextField(blank=True, db_comment='仅用于给充值地址补 Gas / TRX 的热钱包私钥；建议仅管理员可见', default='', verbose_name='手续费钱包私钥'),
        ),
        migrations.RunPython(backfill_sweep_destination_address, migrations.RunPython.noop),
    ]
