# Generated by Django 6.0.4 on 2026-04-09 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='公告标题', max_length=255, verbose_name='公告标题')),
                ('content', models.TextField(db_comment='公告详细内容', verbose_name='公告内容')),
                ('is_active', models.BooleanField(db_comment='公告是否对外生效', default=True, verbose_name='是否生效')),
                ('publish_at', models.DateTimeField(db_comment='公告发布时间', default=django.utils.timezone.now, verbose_name='发布时间')),
                ('expire_at', models.DateTimeField(blank=True, db_comment='公告失效时间，可为空', null=True, verbose_name='失效时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='公告创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'ordering': ('-publish_at',),
            },
        ),
    ]
