# Generated by Django 6.0.4 on 2026-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='cover',
            field=models.ImageField(blank=True, db_comment='公告封面图片', null=True, upload_to='announcements/', verbose_name='封面图片'),
        ),
    ]
