# Generated by Django 6.0.4 on 2026-04-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-publish_at',), 'verbose_name': '公告与指南', 'verbose_name_plural': '公告与指南'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='author_name',
            field=models.CharField(db_comment='详情页作者栏', default='官方团队', max_length=100, verbose_name='作者展示名'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category_key',
            field=models.CharField(blank=True, db_comment='英文短横线 slug，用于 Tab 筛选；空表示仅出现在全部', db_index=True, default='', max_length=64, verbose_name='指南分类标识'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category_label',
            field=models.CharField(blank=True, db_comment='Tab 上显示的中文名，可与 category_key 不同', default='', max_length=64, verbose_name='指南分类展示名'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='duration_display',
            field=models.CharField(blank=True, db_comment='如 12:45', default='', max_length=20, verbose_name='时长展示'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='excerpt',
            field=models.CharField(blank=True, db_comment='新手指南列表副标题，可选', default='', max_length=500, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='guide_type',
            field=models.CharField(choices=[('article', '图文'), ('video', '视频')], db_comment='仅新手指南有意义：图文或视频', default='article', max_length=20, verbose_name='指南形态'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_featured',
            field=models.BooleanField(db_comment='新手指南首页大卡，建议仅一条为 True', default=False, verbose_name='置顶推荐'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='post_type',
            field=models.CharField(choices=[('announcement', '系统公告'), ('newbie_guide', '新手指南')], db_comment='系统公告走原有展示；新手指南走 /api/v1/guides/ 与富文本编辑器', default='announcement', max_length=32, verbose_name='内容类型'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='read_minutes',
            field=models.PositiveSmallIntegerField(db_comment='约读时间展示', default=4, verbose_name='阅读分钟'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, db_comment='可选，便于分享链接', default='', max_length=120, verbose_name='URL 标识'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, db_comment='guide_type=video 时填写', default='', max_length=500, verbose_name='视频地址'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.PositiveIntegerField(db_comment='指南详情接口访问时自增', default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(db_comment='富文本 HTML，新手指南详情同源', verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='cover',
            field=models.ImageField(blank=True, db_comment='指南列表卡片图；可为空', null=True, upload_to='announcements/', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(db_comment='公告或指南标题', max_length=255, verbose_name='标题'),
        ),
    ]
