# Generated by Django 6.0.4 on 2026-04-15 08:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_newbie_guide_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(db_comment='英文短横线，用于接口 category_slug 与前台 Tab', max_length=64, unique=True, verbose_name='分类标识')),
                ('name', models.CharField(db_comment='Tab 上显示的中文名', max_length=64, verbose_name='展示名称')),
                ('sort_order', models.PositiveSmallIntegerField(db_comment='数字越小越靠前', default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '新手指南分类',
                'verbose_name_plural': '新手指南分类',
                'ordering': ('sort_order', 'slug'),
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_file',
            field=models.FileField(blank=True, db_comment='本地上传；与外链二选一即可，均填写时前台优先用本地上传', null=True, upload_to='announcements/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('mp4', 'webm', 'mov', 'm4v', 'ogv', 'mkv'))], verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category_key',
            field=models.CharField(blank=True, db_comment='已废弃：请改用上方「指南分类」；仅兼容历史数据', db_index=True, default='', max_length=64, verbose_name='指南分类标识（旧版）'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category_label',
            field=models.CharField(blank=True, db_comment='已废弃：请改用「新手指南分类」', default='', max_length=64, verbose_name='指南分类展示名（旧版）'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, db_comment='guide_type=video 时可选：YouTube 等外链；无本地上传时使用', default='', max_length=500, verbose_name='视频外链'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='guide_category',
            field=models.ForeignKey(blank=True, db_comment='在「新手指南分类」中维护；选后前台 Tab 与筛选用该分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='announcements.guidecategory', verbose_name='指南分类'),
        ),
    ]
